services:
  app:
    build: .
    ports:
      - "${PROD_WEBSERVER_PORT_MAPPING}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: ${PROD_DATABASE_URL}
      DATABASE_USERNAME: ${PROD_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${PROD_DATABASE_PASSWORD}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_CORS_ALLOWED_METHODS: ${APP_CORS_ALLOWED_METHODS}
      APP_CORS_ALLOWED_HEADERS: ${APP_CORS_ALLOWED_HEADERS}
      APP_CORS_ALLOW_CREDENTIALS: ${APP_CORS_ALLOW_CREDENTIALS}
      APP_CORS_MAX_AGE: ${APP_CORS_MAX_AGE}

volumes:
  pgdata: