spring.datasource.url=jdbc:postgresql://localhost:${SCRATCH_DATABASE_PORT_MAPPING}/scratch_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true
spring.flyway.clean-disabled=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.beans.factory=DEBUG

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.cors.allowed-methods=${APP_CORS_ALLOWED_METHODS}
app.cors.allowed-headers=${APP_CORS_ALLOWED_HEADERS}
app.cors.allow-credentials=${APP_CORS_ALLOW_CREDENTIALS}
app.cors.max-age=${APP_CORS_MAX_AGE}