spring.datasource.url=jdbc:postgresql://localhost:${SCRATCH_DATABASE_PORT_MAPPING}/scratch_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true
spring.flyway.clean-disabled=false

logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate